version: "3.9"
services:
    #webapirest:
        # image: webapirest
        # #    - ASPNETCORE_URL=http://0.0.0.0:80
        # build:
        #     context: ./myapirest
        #     dockerfile: Dockertfile
        # ports: 
        #    - "8081:80" 
        # working_dir: /app
        # volumes:
        #     - "..:/app"
        # container_name: myapirest
        # # command: sleep infinity
        # # dependeds_on: 
        # #     - sql-server-db


    sql-server-db:
        container_name: sql-server-db
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Admin123"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"

    postgresql-db:
        image: postgres:latest
        environment:
          - POSTGRES_DB=mybd
          - POSTGRES_USER=admin
          - POSTGRES_PASSWORD=Admin123
        ports:
        - "5432:5432"
        volumes:
        - postgresql-data:/var/lib/postgresql/data
volumes:  
     postgresql-data:
        external: true