// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Servicio.Datos.Context;

namespace Servicio.Datos.Migrations.Npgsql
{
    [DbContext(typeof(BDContext_Npgsql))]
    [Migration("20210119083621_InicialMigracion")]
    partial class InicialMigracion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Servicio.Entidad.Models.Comun.Institucion", b =>
                {
                    b.Property<int>("cod_institucion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(550)
                        .HasColumnType("character varying(550)");

                    b.Property<string>("siglas")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("cod_institucion");

                    b.ToTable("Institucion", "Comun");
                });

            modelBuilder.Entity("Servicio.Entidad.Models.Comun.Sucursales", b =>
                {
                    b.Property<int>("cod_sucursal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("cod_institucion")
                        .HasColumnType("integer");

                    b.Property<string>("sucursal")
                        .IsRequired()
                        .HasMaxLength(550)
                        .HasColumnType("character varying(550)");

                    b.HasKey("cod_sucursal");

                    b.HasIndex("cod_institucion");

                    b.ToTable("Sucursales", "Comun");
                });

            modelBuilder.Entity("Servicio.Entidad.Models.Comun.Sucursales", b =>
                {
                    b.HasOne("Servicio.Entidad.Models.Comun.Institucion", "Institucion")
                        .WithMany("Surcursales")
                        .HasForeignKey("cod_institucion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institucion");
                });

            modelBuilder.Entity("Servicio.Entidad.Models.Comun.Institucion", b =>
                {
                    b.Navigation("Surcursales");
                });
#pragma warning restore 612, 618
        }
    }
}
